default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cardoni_net_development

test:
  <<: *default
  database: cardoni_net_test

production:
  <<: *default
  database: cardoni_net_production
  username: cardoni_net
  password: cardoni_net
  # TODO: Store password in environment var
  # password: <%= ENV['CARDONI_NET_DATABASE_PASSWORD'] %>
