default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cardoni_net_development

test:
  <<: *default
  database: cardoni_net_test

production:
  <<: *default
  database: cardoni_net_production
  username: cardoni_net
  password: cardoni_net
  # TODO: Get pow (and thus .powenv files) working in OS X Yosemite
  # password: <%= ENV['CARDONI_NET_DATABASE_PASSWORD'] %>
